set nocompatible
set runtimepath=~/.config/jnetterf/etc/vim,$VIMRUNTIME

execute pathogen#infect()
syntax on
filetype plugin indent on
filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab
colorscheme distinguished
filetype indent plugin on

let g:CommandTFileScanner = "git"

" keep the selection
vmap > >gv
vmap < <gv
